FROM mysql:latest
MAINTAINER Romain VERMOREL <romain.vermorel@gmail.com>
ADD choralegourmande.sql /docker-entrypoint-initdb.d/choralegourmande.sql
ADD choralegourmande.cnf /etc/mysql/conf.d/choralegourmande.cnf